import { createFailureRule } from "@/simulations/engine/failures";
import type { SimulationDefinition } from "@/simulations/engine/types";

export const simulatedLoginCredentials = {
  email: "student@example.com",
  password: "learn123",
} as const;

export const simulatedSignupCredentials = {
  name: "Mariama",
  email: "mariama@example.com",
  password: "learn123",
} as const;

export const loginSimulationDefinition: SimulationDefinition = {
  id: "login-prototype",
  title: "What happens when you log in?",
  steps: [
    {
      id: "request-created",
      title: "Request created",
      description: "The browser packages the simulated email and password into an HTTP request.",
      source: "browser",
      target: "middleware",
      duration: 900,
      action: "create-request",
      inspectable: true,
      instructorPrompt: "What information must the browser send before the server can make a decision?",
      payload: {
        kind: "request",
        headline: "POST /api/login",
        method: "POST",
        path: "/api/login",
        headers: [
          { name: "Content-Type", value: "application/json" },
          { name: "Accept", value: "application/json" },
        ],
        body: '{\n  "email": "student@example.com",\n  "password": "••••••••"\n}',
      },
    },
    {
      id: "request-sent",
      title: "Request sent",
      description: "The POST request leaves the browser and travels to the server boundary.",
      source: "browser",
      target: "middleware",
      duration: 760,
      action: "send-request",
      inspectable: true,
      pauseAfter: true,
      payload: {
        kind: "request",
        headline: "POST /api/login",
        method: "POST",
        path: "/api/login",
        headers: [
          { name: "Content-Type", value: "application/json" },
          { name: "Content-Length", value: "67" },
        ],
        body: '{\n  "email": "student@example.com",\n  "password": "••••••••"\n}',
      },
    },
    {
      id: "middleware-logging",
      title: "Request logged",
      description: "Logging middleware records the request method, route, and time without saving the password.",
      source: "middleware",
      target: "middleware",
      duration: 620,
      action: "log-request",
      inspectable: false,
    },
    {
      id: "validation-middleware",
      title: "Input validated",
      description: "Validation middleware checks that the email and password fields have acceptable shapes.",
      source: "middleware",
      target: "router",
      duration: 740,
      action: "validate-request",
      inspectable: false,
    },
    {
      id: "router",
      title: "Route matched",
      description: "The router matches POST /api/login to the login controller.",
      source: "router",
      target: "controller",
      duration: 680,
      action: "match-route",
      inspectable: false,
    },
    {
      id: "auth-service",
      title: "Authentication service called",
      description: "The controller asks the authentication service to verify the submitted credentials.",
      source: "controller",
      target: "service",
      duration: 720,
      action: "call-service",
      inspectable: false,
    },
    {
      id: "database-query",
      title: "User record queried",
      description: "The service asks the database for the user record associated with this email.",
      source: "service",
      target: "database",
      duration: 820,
      action: "query-database",
      inspectable: true,
      pauseAfter: true,
      instructorPrompt: "Why is a database lookup needed before the server can check a password?",
      payload: {
        kind: "request",
        headline: "SELECT user by email",
        headers: [{ name: "Collection", value: "users" }],
        body: '{\n  "email": "student@example.com"\n}',
      },
    },
    {
      id: "password-check",
      title: "Password checked",
      description: "The service compares the submitted password with the stored password hash.",
      source: "service",
      target: "service",
      duration: 850,
      action: "compare-password",
      inspectable: false,
    },
    {
      id: "token-generated",
      title: "Session token generated",
      description: "After a successful comparison, the server creates a simulated session token.",
      source: "service",
      target: "token",
      duration: 760,
      action: "create-token",
      inspectable: true,
      payload: {
        kind: "response",
        headline: "Simulated session",
        headers: [{ name: "Token-Type", value: "Bearer" }],
        body: '{\n  "token": "uth_demo_••••••••",\n  "role": "student"\n}',
      },
    },
    {
      id: "response-sent",
      title: "Response sent",
      description: "The server returns a 200 response and the simulated session to the browser.",
      source: "server",
      target: "browser",
      duration: 780,
      action: "send-response",
      inspectable: true,
      pauseAfter: true,
      payload: {
        kind: "response",
        headline: "200 OK",
        statusCode: 200,
        headers: [
          { name: "Content-Type", value: "application/json" },
          { name: "Cache-Control", value: "no-store" },
        ],
        body: '{\n  "authenticated": true,\n  "role": "student"\n}',
      },
    },
    {
      id: "authenticated",
      title: "Dashboard shown",
      description: "The browser stores the simulated session and reveals the learner dashboard.",
      source: "browser",
      duration: 850,
      action: "show-result",
      inspectable: false,
    },
  ],
  failureRules: {
    // Each rule stops at the component that is actually responsible for the check.
    "invalid-request": createFailureRule("invalid-request", "validation-middleware"),
    "missing-route": createFailureRule("missing-route", "router"),
    "database-unavailable": createFailureRule("database-unavailable", "database-query"),
    "wrong-password": createFailureRule("wrong-password", "password-check"),
    "invalid-token": createFailureRule("invalid-token", "token-generated"),
    "wrong-role": createFailureRule("wrong-role", "response-sent"),
  },
};

export const signupSimulationDefinition: SimulationDefinition = {
  id: "signup-prototype",
  title: "What happens when you sign up?",
  steps: [
    {
      id: "request-created",
      title: "Sign-up request created",
      description: "The browser packages the name, email, and password into a new-account request.",
      source: "browser",
      target: "middleware",
      duration: 900,
      action: "create-request",
      inspectable: true,
      instructorPrompt: "Which fields does the server need before it can create an account?",
      payload: {
        kind: "request",
        headline: "POST /api/signup",
        method: "POST",
        path: "/api/signup",
        headers: [
          { name: "Content-Type", value: "application/json" },
          { name: "Accept", value: "application/json" },
        ],
        body: '{\n  "name": "Mariama",\n  "email": "mariama@example.com",\n  "password": "••••••••"\n}',
      },
    },
    {
      id: "request-sent",
      title: "Request sent",
      description: "The POST request leaves the browser and travels to the server boundary.",
      source: "browser",
      target: "middleware",
      duration: 760,
      action: "send-request",
      inspectable: true,
      pauseAfter: true,
      payload: {
        kind: "request",
        headline: "POST /api/signup",
        method: "POST",
        path: "/api/signup",
        headers: [
          { name: "Content-Type", value: "application/json" },
          { name: "Content-Length", value: "92" },
        ],
        body: '{\n  "name": "Mariama",\n  "email": "mariama@example.com",\n  "password": "••••••••"\n}',
      },
    },
    {
      id: "middleware-logging",
      title: "Request logged",
      description: "Logging middleware records the route and time without recording the password.",
      source: "middleware",
      target: "middleware",
      duration: 620,
      action: "log-request",
      inspectable: false,
    },
    {
      id: "validation-middleware",
      title: "Input validated",
      description: "Validation checks the name, email format, password length, and confirmation.",
      source: "middleware",
      target: "router",
      duration: 740,
      action: "validate-request",
      inspectable: false,
    },
    {
      id: "router",
      title: "Route matched",
      description: "The router matches POST /api/signup to the account controller.",
      source: "router",
      target: "controller",
      duration: 680,
      action: "match-route",
      inspectable: false,
    },
    {
      id: "account-service",
      title: "Account service called",
      description: "The controller asks the account service to create a new user safely.",
      source: "controller",
      target: "service",
      duration: 720,
      action: "call-service",
      inspectable: false,
    },
    {
      id: "email-availability",
      title: "Email availability checked",
      description: "The service queries the users table to make sure the email is not already registered.",
      source: "service",
      target: "database",
      duration: 820,
      action: "query-database",
      inspectable: true,
      pauseAfter: true,
      instructorPrompt: "Why must the server check this before inserting a new user?",
      payload: {
        kind: "request",
        headline: "Check unique email",
        headers: [{ name: "Collection", value: "users" }],
        body: '{\n  "email": "mariama@example.com",\n  "exists": false\n}',
      },
    },
    {
      id: "password-hashed",
      title: "Password hashed",
      description: "The service converts the password into a one-way hash before anything is stored.",
      source: "service",
      target: "service",
      duration: 850,
      action: "hash-password",
      inspectable: false,
    },
    {
      id: "user-created",
      title: "User record created",
      description: "The database stores the new profile and password hash, never the original password.",
      source: "service",
      target: "database",
      duration: 820,
      action: "create-record",
      inspectable: true,
      payload: {
        kind: "request",
        headline: "INSERT new user",
        headers: [{ name: "Collection", value: "users" }],
        body: '{\n  "name": "Mariama",\n  "email": "mariama@example.com",\n  "passwordHash": "$demo$••••••••"\n}',
      },
    },
    {
      id: "token-generated",
      title: "Session token generated",
      description: "After the record is created, the server generates a simulated session for the new user.",
      source: "service",
      target: "token",
      duration: 760,
      action: "create-token",
      inspectable: true,
      payload: {
        kind: "response",
        headline: "Simulated session",
        headers: [{ name: "Token-Type", value: "Bearer" }],
        body: '{\n  "token": "uth_demo_••••••••",\n  "role": "student"\n}',
      },
    },
    {
      id: "response-sent",
      title: "Created response sent",
      description: "The server returns 201 Created with the new profile and simulated session.",
      source: "server",
      target: "browser",
      duration: 780,
      action: "send-response",
      inspectable: true,
      pauseAfter: true,
      payload: {
        kind: "response",
        headline: "201 Created",
        statusCode: 201,
        headers: [
          { name: "Content-Type", value: "application/json" },
          { name: "Cache-Control", value: "no-store" },
        ],
        body: '{\n  "created": true,\n  "role": "student"\n}',
      },
    },
    {
      id: "account-ready",
      title: "Welcome screen shown",
      description: "The browser stores the simulated session and welcomes the new account.",
      source: "browser",
      duration: 850,
      action: "show-result",
      inspectable: false,
    },
  ],
  failureRules: {
    "invalid-request": createFailureRule("invalid-request", "validation-middleware"),
    "missing-route": createFailureRule("missing-route", "router"),
    "database-unavailable": createFailureRule("database-unavailable", "email-availability"),
    "email-taken": createFailureRule("email-taken", "email-availability"),
  },
};
